const CATEGORIES = ['인문·철학','사회·경제','과학·기술','문학·에세이','예술·문화','자기계발'];
const PURPOSES = ['교양 넓히기','전공·학습 탐구','진로·성장','휴식·힐링'];
const INITIAL_BOOKS = [
  {id:'b1',title:'물고기는 존재하지 않는다',author:'룰루 밀러',publisher:'곰출판',pages:300,category:'과학·기술',purposes:['교양 넓히기','휴식·힐링'],color:'sage',description:'분류와 질서를 믿었던 한 과학자의 삶을 따라가며, 혼돈 속에서 삶의 의미를 발견하는 이야기입니다.'},
  {id:'b2',title:'불편한 편의점',author:'김호연',publisher:'나무옆의자',pages:268,category:'문학·에세이',purposes:['휴식·힐링','교양 넓히기'],color:'orange',description:'서울의 작은 편의점에 모인 사람들의 사연을 통해 일상의 위로와 관계의 온기를 전하는 소설입니다.'},
  {id:'b3',title:'아주 작은 습관의 힘',author:'제임스 클리어',publisher:'비즈니스북스',pages:360,category:'자기계발',purposes:['진로·성장'],color:'cream',description:'작은 행동을 꾸준히 이어가는 방법을 살펴보며, 원하는 일상과 공부 습관을 만들어가는 책입니다.'},
  {id:'b4',title:'사피엔스',author:'유발 하라리',publisher:'김영사',pages:636,category:'인문·철학',purposes:['교양 넓히기','전공·학습 탐구'],color:'cream',description:'인류의 역사를 넓게 조망하며 우리가 어떻게 협력하고 사회를 만들어왔는지 질문합니다.'},
  {id:'b5',title:'돈의 심리학',author:'모건 하우절',publisher:'인플루엔셜',pages:396,category:'사회·경제',purposes:['교양 넓히기','진로·성장'],color:'navy',description:'돈을 대하는 태도와 선택에 숨은 심리를 통해 경제적 의사결정을 생각해보는 책입니다.'},
  {id:'b6',title:'여행의 이유',author:'김영하',publisher:'문학동네',pages:216,category:'문학·에세이',purposes:['휴식·힐링','교양 넓히기'],color:'blue',description:'낯선 곳으로 떠나는 경험과 돌아오는 마음을 통해 여행과 삶의 의미를 돌아보는 에세이입니다.'},
  {id:'b7',title:'코스모스',author:'칼 세이건',publisher:'사이언스북스',pages:719,category:'과학·기술',purposes:['교양 넓히기','전공·학습 탐구'],color:'navy',description:'우주의 탄생부터 생명과 문명까지, 과학적 탐구가 열어주는 광대한 세계를 만납니다.'},
  {id:'b8',title:'방구석 미술관',author:'조원재',publisher:'블랙피쉬',pages:344,category:'예술·문화',purposes:['교양 넓히기','휴식·힐링'],color:'pink',description:'예술가의 삶과 작품 뒤에 숨은 이야기를 따라가며 미술을 더 친근하게 만나는 입문서입니다.'},
  {id:'b9',title:'데미안',author:'헤르만 헤세',publisher:'민음사',pages:239,category:'문학·에세이',purposes:['휴식·힐링','진로·성장'],color:'sage',description:'자신의 내면과 마주하며 성장하는 청년의 여정을 통해 나다운 삶에 대해 생각해보는 소설입니다.'},
  {id:'b10',title:'왜 일하는가',author:'이나모리 가즈오',publisher:'다산북스',pages:272,category:'자기계발',purposes:['진로·성장'],color:'orange',description:'일을 대하는 자세와 몰입의 의미를 돌아보며 앞으로의 진로와 삶의 방향을 고민하게 합니다.'},
  {id:'b11',title:'정의란 무엇인가',author:'마이클 샌델',publisher:'와이즈베리',pages:404,category:'인문·철학',purposes:['전공·학습 탐구','교양 넓히기'],color:'blue',description:'익숙한 사회적 딜레마를 다양한 철학적 관점으로 살펴보며 공정함과 정의를 질문합니다.'},
  {id:'b12',title:'팩트풀니스',author:'한스 로슬링 외',publisher:'김영사',pages:474,category:'사회·경제',purposes:['전공·학습 탐구','교양 넓히기'],color:'pink',description:'세상을 바라보는 직관을 데이터와 비교하며 사실에 근거해 생각하는 방법을 소개합니다.'}
];
const BOOK_KEY='library-books-v1', SAVE_KEY='library-saved-v1';
const $ = (s) => document.querySelector(s);
const esc = (v) => String(v).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return Array.isArray(v)?v:fallback;}catch{return fallback;}}
let books=read(BOOK_KEY,INITIAL_BOOKS).filter(b=>b&&typeof b.id==='string'&&typeof b.title==='string'&&Array.isArray(b.purposes));
let saved=read(SAVE_KEY,[]).filter(id=>books.some(b=>b.id===id));
function persist(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{toast('저장 공간을 사용할 수 없습니다. 브라우저 설정을 확인해주세요.');return false;}}
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2800);}
function cover(b){return `<div class="book-cover ${['sage','orange','cream','navy','pink','blue'].includes(b.color)?b.color:'sage'}" aria-hidden="true"><span class="cover-top">LIBRARY COLLECTION</span><span class="cover-title">${esc(b.title)}</span><span class="cover-author">${esc(b.author)}</span><span class="cover-bottom">A NEW PERSPECTIVE</span></div>`;}
document.querySelectorAll('.dialog-close').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}}));
if($('#book-grid')){
  let filters={categories:[],purpose:'all',length:'all'}, showingSaved=false, hasSearched=false;
  $('#category-options').innerHTML=CATEGORIES.map((c,i)=>`<label><input type="checkbox" name="category" value="${esc(c)}"><span>${esc(c)}</span></label>`).join('');
  $('#purpose-options').innerHTML=['상관없어요',...PURPOSES].map((p,i)=>`<label><input type="radio" name="purpose" value="${i?esc(p):'all'}" ${i?'':'checked'}>${esc(p)}</label>`).join('');
  function matchesLength(b){return filters.length==='all'||(filters.length==='short'&&b.pages<=250)||(filters.length==='medium'&&b.pages>250&&b.pages<=400)||(filters.length==='long'&&b.pages>400);}
  function reason(b){if(showingSaved)return '다시 읽고 싶은 순간을 위해 내 책장에 담아둔 책이에요.';const parts=[];if(filters.categories.includes(b.category))parts.push(`${b.category} 분야에 대한 관심`);if(b.purposes.includes(filters.purpose))parts.push(`‘${filters.purpose}’ 목적`);return parts.length?`${parts.join('과 ')}에 어울리는 책이에요.`:`${b.category} 분야에서 ${b.purposes[0]}에 어울리는 책이에요.`;}
  function render(){
    let list=books.filter(b=>showingSaved?saved.includes(b.id):(!filters.categories.length||filters.categories.includes(b.category))&&(filters.purpose==='all'||b.purposes.includes(filters.purpose))&&matchesLength(b));
    if($('#sort').value==='title')list.sort((a,b)=>a.title.localeCompare(b.title,'ko'));if($('#sort').value==='pages')list.sort((a,b)=>a.pages-b.pages);
    $('#saved-count').textContent=saved.length;$('#saved-toggle').classList.toggle('active',showingSaved);$('#saved-toggle').setAttribute('aria-pressed',showingSaved);
    $('#results-title').textContent=showingSaved?'내 책장':hasSearched?'당신을 위한 추천 도서':'새로운 발견을 위한 책';
    $('#results-kicker').textContent=showingSaved?'YOUR BOOKSHELF':'CURATED FOR YOU';
    $('#results-description').textContent=showingSaved?'마음에 담아둔 책을 한곳에서 다시 만나보세요.':hasSearched?'선택한 조건에 맞는 책들을 모았어요. 다음 한 권을 만나보세요.':'다양한 분야의 책에서 나만의 취향을 발견해보세요.';
    $('#result-count').textContent=`${list.length}권`;
    $('#selection-summary').textContent=showingSaved?'♡ 나만의 읽기 목록':hasSearched?`✦ ${[...filters.categories,filters.purpose==='all'?'':filters.purpose,filters.length==='all'?'':$('#length').selectedOptions[0].textContent.split(' · ')[0]].filter(Boolean).join(' · ')||'모든 분야의 책'}`:'✦ 사서의 큐레이션';
    $('#book-grid').innerHTML=list.map(b=>`<article class="book-card"><div class="cover-area">${cover(b)}<button class="bookmark ${saved.includes(b.id)?'saved':''}" data-save="${esc(b.id)}" aria-label="${esc(b.title)} ${saved.includes(b.id)?'책장에서 빼기':'책장에 담기'}" aria-pressed="${saved.includes(b.id)}">${saved.includes(b.id)?'♥':'♡'}</button></div><div class="card-body"><span class="category-tag">${esc(b.category)}</span><h3 class="book-title">${esc(b.title)}</h3><div class="book-meta">${esc(b.author)} · ${esc(b.publisher)}</div><p class="book-description">${esc(b.description)}</p><div class="card-bottom"><span>${esc(b.pages)}쪽 · ${esc(b.purposes[0])}</span><button class="detail-button" data-detail="${esc(b.id)}">자세히 보기 ↗</button></div></div></article>`).join('');
    $('#empty').classList.toggle('hidden',list.length>0);$('#empty p').textContent=showingSaved?'도서 카드의 하트를 눌러 읽고 싶은 책을 담아보세요.':'관심 분야, 독서 목적 또는 분량 조건을 넓혀보세요.';
  }
  function toggleSave(id){const next=saved.includes(id)?saved.filter(s=>s!==id):[...saved,id];if(!persist(SAVE_KEY,next))return;saved=next;toast(saved.includes(id)?'내 책장에 담았어요.':'내 책장에서 뺐어요.');render();}
  document.addEventListener('click',event=>{const save=event.target.closest('[data-save]');if(save){toggleSave(save.dataset.save);if($('#book-dialog').open)showDetail(save.dataset.save);}const detail=event.target.closest('[data-detail]');if(detail)showDetail(detail.dataset.detail);});
  function showDetail(id){const b=books.find(b=>b.id===id);if(!b)return;$('#dialog-content').innerHTML=`<div class="dialog-book">${cover(b)}<div><span class="category-tag">${esc(b.category)}</span><h2 id="detail-title">${esc(b.title)}</h2><p class="book-meta">${esc(b.author)}<br>${esc(b.publisher)} · ${esc(b.pages)}쪽</p></div></div><p class="detail-description">${esc(b.description)}</p><div class="recommend-reason"><strong>✦ 이 책을 추천하는 이유</strong><br>${esc(reason(b))}<br>독서 목적: ${b.purposes.map(esc).join(' · ')}</div><button class="primary full" data-save="${esc(b.id)}">${saved.includes(id)?'♥ 내 책장에서 빼기':'♡ 내 책장에 담기'}</button><p class="catalog-note">쪽수는 판본에 따라 다를 수 있습니다. 표지는 디자인용 이미지이며, 실제 도서 표지와 다릅니다. 소장·대출 여부는 소속 대학도서관에서 확인해주세요.</p>`;$('#book-dialog').setAttribute('aria-labelledby','detail-title');if(!$('#book-dialog').open)$('#book-dialog').showModal();}
  $('#recommend-form').addEventListener('submit',event=>{event.preventDefault();filters={categories:[...document.querySelectorAll('input[name=category]:checked')].map(e=>e.value),purpose:document.querySelector('input[name=purpose]:checked').value,length:$('#length').value};showingSaved=false;hasSearched=true;render();if(innerWidth<701)$('.results').scrollIntoView({behavior:'smooth'});});
  $('#reset-filters').addEventListener('click',()=>{$('#recommend-form').reset();filters={categories:[],purpose:'all',length:'all'};showingSaved=false;hasSearched=false;$('#sort').value='recommended';render();});
  $('#saved-toggle').addEventListener('click',()=>{showingSaved=!showingSaved;render();$('#finder').scrollIntoView({behavior:'smooth'});});$('#sort').addEventListener('change',render);render();
}
if($('#admin-books')){
  $('#edit-category').innerHTML=CATEGORIES.map(c=>`<option>${esc(c)}</option>`).join('');$('#edit-purposes').innerHTML=PURPOSES.map(p=>`<label><input type="checkbox" name="purposes" value="${esc(p)}">${esc(p)}</label>`).join('');
  function renderAdmin(){const query=$('#admin-search').value.trim().toLocaleLowerCase();const list=books.filter(b=>`${b.title} ${b.author}`.toLocaleLowerCase().includes(query));$('#stat-books').textContent=books.length;$('#stat-categories').textContent=new Set(books.map(b=>b.category)).size;$('#stat-saved').textContent=saved.length;$('#admin-count').textContent=`${list.length}권`;$('#admin-empty').classList.toggle('hidden',list.length>0);$('#admin-books').innerHTML=list.map(b=>`<tr><td><strong>${esc(b.title)}</strong><small>${esc(b.author)} · ${esc(b.publisher)}</small></td><td><span class="category-tag">${esc(b.category)}</span></td><td>${b.purposes.map(esc).join(', ')}</td><td>${esc(b.pages)}쪽</td><td><button class="table-button" data-edit="${esc(b.id)}" aria-label="${esc(b.title)} 수정">수정</button><button class="table-button delete" data-delete="${esc(b.id)}" aria-label="${esc(b.title)} 삭제">삭제</button></td></tr>`).join('');}
  function editBook(id){const form=$('#book-form');form.reset();form.elements.id.value='';$('#form-error').textContent='';const book=books.find(b=>b.id===id);$('#edit-title').textContent=book?'도서 수정':'새 도서 등록';if(book){['id','title','author','publisher','pages','category','color','description'].forEach(k=>form.elements[k].value=book[k]);form.querySelectorAll('[name=purposes]').forEach(el=>el.checked=book.purposes.includes(el.value));}$('#edit-dialog').setAttribute('aria-labelledby','edit-title');$('#edit-dialog').showModal();}
  $('#add-book').addEventListener('click',()=>editBook());$('#cancel-edit').addEventListener('click',()=>$('#edit-dialog').close());$('#admin-search').addEventListener('input',renderAdmin);
  $('#admin-books').addEventListener('click',event=>{const edit=event.target.closest('[data-edit]');if(edit)editBook(edit.dataset.edit);const del=event.target.closest('[data-delete]');if(del){const b=books.find(b=>b.id===del.dataset.delete);if(!confirm(`‘${b.title}’ 도서를 삭제할까요? 추천 목록과 내 책장에서 제거됩니다.`))return;const next=books.filter(v=>v.id!==b.id);if(!persist(BOOK_KEY,next))return;books=next;saved=saved.filter(id=>id!==b.id);persist(SAVE_KEY,saved);renderAdmin();toast('도서를 삭제했습니다.');}});
  $('#book-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.target),purposes=data.getAll('purposes');if(!purposes.length){$('#form-error').textContent='독서 목적을 1개 이상 선택해주세요.';return;}const book={id:data.get('id')||`book-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,title:data.get('title').trim(),author:data.get('author').trim(),publisher:data.get('publisher').trim(),pages:Number(data.get('pages')),category:data.get('category'),color:data.get('color'),description:data.get('description').trim(),purposes};if(!book.title||!book.author||!book.publisher||!book.description){$('#form-error').textContent='공백만 입력할 수 없습니다. 모든 항목을 채워주세요.';return;}const next=books.some(b=>b.id===book.id)?books.map(b=>b.id===book.id?book:b):[book,...books];if(!persist(BOOK_KEY,next))return;books=next;$('#edit-dialog').close();renderAdmin();toast('도서 정보를 저장했습니다.');});renderAdmin();
}
