const paths={book:'M3 4h6a4 4 0 0 1 3 2 4 4 0 0 1 3-2h6v15h-6a4 4 0 0 0-3 2 4 4 0 0 0-3-2H3z M12 6v15',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',check:'m5 12 4 4L19 6',spark:'m12 3 3 6 6 3-6 3-3 6-3-6-6-3 6-3z',pen:'m15 4 5 5 M4 20l5-1L21 7a2 2 0 0 0-5-5L4 14z',desk:'M3 11h18 M5 11v10 M19 11v10 M7 8V3h10v5 M7 17h10',laptop:'M5 4h14v12H5z M2 20h20l-3-4H5z',compass:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M16 8l-3 5-5 3 3-5z',message:'M21 11a9 9 0 0 1-9 9H3l1-5a9 9 0 1 1 17-4 M8 10h8 M8 14h5',leaf:'M20 3C7 2 2 8 6 15s15 4 14-12z M5 21 16 8'};
function icon(name){return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.book}"/></svg>`}
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
const situations=[{id:'assignment',icon:'search',title:'과제에 쓸 자료가 필요해요',desc:'주제에 맞는 책, 논문, 믿을 만한 자료 찾기'},{id:'research',icon:'pen',title:'논문·연구를 준비하고 있어요',desc:'선행연구 조사부터 참고문헌 관리까지'},{id:'space',icon:'desk',title:'공부할 공간을 찾고 있어요',desc:'좌석·공간 현황과 실제 이용신청 확인'},{id:'remote',icon:'laptop',title:'도서관 밖에서 이용하고 싶어요',desc:'집에서도 전자책과 학술자료 이용하기'},{id:'first',icon:'compass',title:'도서관 이용이 처음이에요',desc:'대출 방법부터 나에게 필요한 이용 교육'},{id:'rest',icon:'leaf',title:'책과 함께 쉬어가고 싶어요',desc:'전자책과 북큐레이션으로 읽을 책 고르기'}];
const services = libraryServices;
const selected=new Set();const grid=document.getElementById('situations');const recommend=document.getElementById('recommend');const results=document.getElementById('results');let lastTrigger=null;
grid.innerHTML=situations.map(s=>`<button type="button" class="situation" data-id="${s.id}" aria-pressed="false"><span class="tile-icon">${icon(s.icon)}</span><span class="tile-check">${icon('check')}</span><strong>${s.title}</strong><small>${s.desc}</small></button>`).join('');
grid.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;const id=button.dataset.id;selected.has(id)?selected.delete(id):selected.add(id);button.setAttribute('aria-pressed',String(selected.has(id)));recommend.disabled=!selected.size;document.getElementById('selection-count').textContent=selected.size?`${selected.size}개의 상황을 선택했어요. 나에게 맞는 서비스를 확인해보세요.`:'상황을 선택하면 추천을 시작할 수 있어요.';results.hidden=true;});
recommend.addEventListener('click',()=>{if(!selected.size)return;const matches=services.map((service,index)=>({service,index,score:service.tags.filter(t=>selected.has(t)).length})).filter(s=>s.score).sort((a,b)=>b.score-a.score||a.index-b.index);document.getElementById('result-description').textContent=`선택한 ${selected.size}개의 상황에 맞는 서비스 ${matches.length}개를 찾았어요. 관련성이 높은 순서로 안내해드려요.`;document.getElementById('result-grid').innerHTML=matches.map(({service,index,score})=>`<article class="result-card"><span class="match">${score}개 상황과 연결된 서비스</span><h3>${service.title}</h3><p>${service.desc}</p><button data-service="${index}" aria-label="${service.title} 이용 방법 보기">이용 방법 알아보기 <span aria-hidden="true">↗</span></button></article>`).join('');results.hidden=false;document.getElementById('result-title').focus({preventScroll:true});results.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});});
document.getElementById('reset').addEventListener('click',()=>{selected.clear();grid.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed','false'));recommend.disabled=true;results.hidden=true;document.getElementById('selection-count').textContent='상황을 선택하면 추천을 시작할 수 있어요.';grid.querySelector('button').focus();});
const dialog=document.getElementById('detail');document.getElementById('result-grid').addEventListener('click',e=>{const button=e.target.closest('[data-service]');if(!button)return;lastTrigger=button;const service=services[Number(button.dataset.service)];document.getElementById('dialog-content').innerHTML=`<h2 id="dialog-title">${service.title}</h2><p>${service.desc}</p><h3>이렇게 이용해보세요</h3><ol>${service.steps.map(step=>`<li>${step}</li>`).join('')}</ol><h3>이용 조건 · 확인할 사항</h3><p class="dialog-note">${service.prepare}</p><div class="official-sources"><h3>공식 안내로 이어가기</h3>${[{title:service.sourceTitle,url:service.url},service.extraSource,...(service.moreSources||[])].filter(Boolean).map(source=>`<a href="${source.url}" target="_blank" rel="noopener noreferrer">${source.title} <span aria-hidden="true">↗</span><span class="sr-only"> (새 창)</span></a>`).join('')}</div><p class="source-date">공식 안내 확인: 2026.09.09 · 신청은 도서관 홈페이지에서 진행합니다.</p>`;dialog.setAttribute('aria-labelledby','dialog-title');dialog.showModal();});
function closeDialog(){dialog.close();}document.getElementById('close-dialog').addEventListener('click',closeDialog);document.getElementById('dialog-done').addEventListener('click',closeDialog);dialog.addEventListener('close',()=>lastTrigger?.focus());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
